services:
  mysql-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gapicbsg
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: gapicbsg
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8091:80"

  corebanking:
    image: corebanking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081-8084:8080
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/corebanking?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gapicbsg

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d