spring:
  application:
    name: corebanking
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db:3306/corebanking?createDatabaseIfNotExist=true
    username: root
    password: gapicbsg

  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    health:
      show-details: always
      probes:
        enabled: true
    web:
      exposure:
        include: "beans,env,health,info,metrics,mappings,prometheus"

logging:
  level:
    root: INFO